name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            Thank you for posting a issue!
        pr-message: |
            Thank you for your first contribution to the project! I will take a look at you pull request as soon as possible.
            This will make it easier to review the code and get it merged faster. Thanks!
